2021/08/23 22:30:43 [error] 17131#0: *47 open() "/Users/shin/Desktop/Git/django/Day08/Day08_root/static/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 22:31:47 [error] 17131#0: *47 open() "/Users/shin/Desktop/Git/django/Day08/Day08_root/static/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 22:31:48 [error] 17131#0: *47 open() "/Users/shin/Desktop/Git/django/Day08/Day08_root/static/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 22:31:48 [error] 17131#0: *47 open() "/Users/shin/Desktop/Git/django/Day08/Day08_root/static/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 22:33:16 [error] 17330#0: *52 open() "/Users/shin/Desktop/Git/django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 22:33:17 [error] 17330#0: *52 open() "/Users/shin/Desktop/Git/django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 22:33:17 [error] 17330#0: *52 open() "/Users/shin/Desktop/Git/django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 22:33:17 [error] 17330#0: *52 open() "/Users/shin/Desktop/Git/django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 22:35:01 [error] 17330#0: *56 open() "/Users/shin/Desktop/Git/django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 22:35:02 [error] 17330#0: *56 open() "/Users/shin/Desktop/Git/django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 22:35:05 [error] 17330#0: *57 open() "/Users/shin/Desktop/Git/django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46"
2021/08/23 23:30:14 [error] 20481#0: *19 open() "/Users/shin/Desktop/Git/Django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46", referrer: "http://172.30.1.46/ex00/add-img/"
2021/08/23 23:30:14 [error] 20481#0: *19 open() "/Users/shin/Desktop/Git/Django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46", referrer: "http://172.30.1.46/ex00/add-img/"
2021/08/23 23:30:15 [error] 20481#0: *19 open() "/Users/shin/Desktop/Git/Django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46", referrer: "http://172.30.1.46/ex00/add-img/"
2021/08/23 23:30:15 [error] 20481#0: *19 open() "/Users/shin/Desktop/Git/Django/Day08/static/images/background.jpeg" failed (2: No such file or directory), client: 172.30.1.46, server: 172.30.1.46, request: "GET /static/images/background.jpeg HTTP/1.1", host: "172.30.1.46", referrer: "http://172.30.1.46/ex00/add-img/"
2021/08/24 02:00:14 [error] 26526#0: *128 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 110.70.50.217, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "http://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78:9999"
2021/08/24 02:03:40 [error] 26526#0: *142 client intended to send too large body: 2005999 bytes, client: 110.70.50.217, server: 183.97.150.78, request: "POST /ex00/add-img/ HTTP/1.1", host: "183.97.150.78:9999", referrer: "http://183.97.150.78:9999/ex00/add-img/"
2021/08/24 19:39:01 [error] 11524#0: *152 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 182.172.56.199, server: m1n9.cf, request: "GET /ex00/add-img HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img", host: "m1n9.cf", referrer: "https://www.google.com/"
2021/08/24 19:39:04 [error] 11524#0: *154 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 211.117.24.132, server: m1n9.cf, request: "GET / HTTP/1.1", upstream: "https://127.0.0.1:8000/", host: "m1n9.cf", referrer: "https://www.google.com/"
2021/08/24 19:39:36 [error] 11524#0: *156 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 211.117.24.132, server: m1n9.cf, request: "GET /ex00/add-img HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img", host: "www.m1n9.cf", referrer: "https://www.google.com/"
2021/08/24 20:01:59 [error] 12677#0: *46 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 38.108.182.5, server: 183.97.150.78, request: "GET / HTTP/1.1", upstream: "https://127.0.0.1:8000/", host: "m1n9.cf"
2021/08/24 20:02:29 [error] 12677#0: *48 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 209.242.207.96, server: 183.97.150.78, request: "GET / HTTP/1.1", upstream: "https://127.0.0.1:8000/", host: "m1n9.tk"
2021/08/24 20:02:35 [error] 12677#0: *51 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 192.186.166.201, server: 183.97.150.78, request: "GET / HTTP/1.1", upstream: "https://127.0.0.1:8000/", host: "m1n9.cf"
2021/08/24 20:03:17 [error] 12677#0: *54 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 171.113.63.110, server: 183.97.150.78, request: "GET / HTTP/1.1", upstream: "https://127.0.0.1:8000/", host: "m1n9.cf"
2021/08/24 20:03:54 [error] 12677#0: *58 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 38.108.182.5, server: 183.97.150.78, request: "GET / HTTP/1.1", upstream: "https://127.0.0.1:8000/", host: "m1n9.cf"
2021/08/24 20:07:54 [error] 12677#0: *61 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 181.214.189.186, server: 183.97.150.78, request: "GET / HTTP/1.1", upstream: "https://127.0.0.1:8000/", host: "m1n9.tk"
2021/08/24 20:44:30 [error] 14215#0: *166 peer closed connection in SSL handshake (54: Connection reset by peer) while SSL handshaking to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:44:30 [error] 14215#0: *166 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:44:31 [error] 14215#0: *166 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:44:31 [error] 14215#0: *166 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:44:34 [error] 14215#0: *166 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:44:34 [error] 14215#0: *166 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:44:39 [error] 14215#0: *166 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:44:39 [error] 14215#0: *166 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:44:40 [error] 14215#0: *166 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:44:40 [error] 14215#0: *166 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:44:45 [error] 14256#0: *183 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:44:45 [error] 14256#0: *183 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:44:45 [error] 14256#0: *183 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:44:46 [error] 14256#0: *183 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:44:55 [error] 14256#0: *183 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/show-imgs/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/show-imgs/", host: "183.97.150.78"
2021/08/24 20:44:55 [error] 14256#0: *183 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/show-imgs/"
2021/08/24 20:45:55 [error] 14292#0: *194 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/show-imgs/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/show-imgs/", host: "183.97.150.78"
2021/08/24 20:45:55 [error] 14292#0: *194 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/show-imgs/"
2021/08/24 20:45:56 [error] 14292#0: *194 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/show-imgs/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/show-imgs/", host: "183.97.150.78"
2021/08/24 20:45:56 [error] 14292#0: *194 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/show-imgs/"
2021/08/24 20:45:59 [error] 14292#0: *194 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/show-imgs/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/show-imgs/", host: "183.97.150.78"
2021/08/24 20:45:59 [error] 14292#0: *194 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/show-imgs/"
2021/08/24 20:46:02 [error] 14292#0: *194 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/show-imgs/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/show-imgs/", host: "183.97.150.78"
2021/08/24 20:46:02 [error] 14292#0: *194 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/show-imgs/"
2021/08/24 20:46:08 [error] 14292#0: *194 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:46:08 [error] 14292#0: *194 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:48:13 [error] 14292#0: *219 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:48:44 [error] 14292#0: *219 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:51:30 [error] 14292#0: *228 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:52:00 [error] 14292#0: *228 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:54:35 [error] 15095#0: *237 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:55:06 [error] 15095#0: *237 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:55:37 [error] 15146#0: *249 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /ex00/add-img/ HTTP/1.1", upstream: "https://127.0.0.1:8000/ex00/add-img/", host: "183.97.150.78"
2021/08/24 20:56:07 [error] 15146#0: *249 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 172.30.1.254, server: 183.97.150.78, request: "GET /favicon.ico HTTP/1.1", upstream: "https://127.0.0.1:8000/favicon.ico", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:59:55 [error] 15248#0: *259 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static//images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:59:56 [error] 15248#0: *259 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static//images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:59:57 [error] 15248#0: *259 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static//images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 20:59:57 [error] 15248#0: *259 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static//images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:01:02 [error] 15317#0: *273 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:01:02 [error] 15317#0: *273 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:01:02 [error] 15317#0: *273 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:01:02 [error] 15317#0: *273 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:01:48 [error] 15399#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:01:49 [error] 15399#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:03:42 [error] 15548#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:03:42 [error] 15548#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:03:42 [error] 15548#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:03:42 [error] 15548#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:03:43 [error] 15548#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:05:13 [error] 15548#0: *21 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:05:13 [error] 15548#0: *21 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:05:14 [error] 15548#0: *21 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:06:55 [error] 15820#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:06:55 [error] 15820#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:06:56 [error] 15820#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:09:21 [error] 15948#0: *14 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:13:24 [error] 16791#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:13:24 [error] 16791#0: *3 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: 183.97.150.78, request: "GET /static/images/background.jpeg HTTP/1.1", host: "183.97.150.78", referrer: "https://183.97.150.78/ex00/add-img/"
2021/08/24 21:48:11 [error] 18225#0: *1 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /static/images/background.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/add-img/"
2021/08/24 21:48:12 [error] 18225#0: *1 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /static/images/background.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/add-img/"
2021/08/24 21:48:14 [error] 18225#0: *1 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /static/images/background.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/add-img/"
2021/08/24 21:48:22 [error] 18225#0: *1 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /static/images/background.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/add-img/"
2021/08/24 21:49:58 [error] 18409#0: *1 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /static/images/background.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/add-img/"
2021/08/24 21:49:58 [error] 18409#0: *1 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /static/images/background.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/add-img/"
2021/08/24 21:49:58 [error] 18409#0: *1 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /static/images/background.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/add-img/"
2021/08/24 21:50:04 [error] 18409#0: *1 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/static/images/background.jpeg" failed (13: Permission denied), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /static/images/background.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/add-img/"
2021/08/25 23:54:38 [error] 10815#0: *163 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg" failed (2: No such file or directory), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/show-imgs/"
2021/08/25 23:54:38 [error] 10815#0: *163 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg" failed (2: No such file or directory), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/show-imgs/"
2021/08/25 23:55:51 [error] 10815#0: *164 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg" failed (2: No such file or directory), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/show-imgs/"
2021/08/25 23:55:52 [error] 10815#0: *164 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg" failed (2: No such file or directory), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/show-imgs/"
2021/08/25 23:55:52 [error] 10815#0: *163 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg" failed (2: No such file or directory), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/show-imgs/"
2021/08/25 23:55:52 [error] 10815#0: *164 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg" failed (2: No such file or directory), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/show-imgs/"
2021/08/25 23:55:53 [error] 10815#0: *163 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg" failed (2: No such file or directory), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/show-imgs/"
2021/08/25 23:55:53 [error] 10815#0: *163 open() "/Users/shin/Desktop/Git/Django/Day08/Day08_root/media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg" failed (2: No such file or directory), client: 172.30.1.254, server: king.m1n9.kro.kr, request: "GET /media/photo/2021/08/25/3D971CAD-D203-448E-8753-600AB218AD40.jpeg HTTP/1.1", host: "king.m1n9.kro.kr", referrer: "https://king.m1n9.kro.kr/ex00/show-imgs/"
